declare const Generator: any;
declare const pluralize: any;
declare const parsing: any;
declare const easygraphqlSchemaParser: any;
declare const constants: any;
declare const utils: any;
declare const matching: any;
declare const manageScalars: any;
declare const relationships: any;
