export function matchString(
  s: any
):
  | 'chance.zip()'
  | 'chance.city()'
  | 'chance.street()'
  | 'chance.country()'
  | 'chance.state()'
  | 'chance.latitude()'
  | 'chance.longitude()'
  | 'chance.color()'
  // | 'chance.commerce.product()'
  // | 'chance.commerce.price()'
  | 'getRandomDate()'
  // | 'chance.date.recent()'
  // 'chance.date.past()'
  | 'chance.month()'
  // | 'chance.finance.iban()'
  // | 'chance.finance.bic()'
  // | 'chance.finance.bitcoinAddress()'
  // | 'chance.finance.amount()'
  | 'chance.email()'
  // | 'chance.internet.userName()'
  | 'chance.url()'
  // | 'chance.internet.password()'
  | 'chance.sentence()'
  | 'chance.paragraph()'
  | 'chance.last()'
  | 'chance.first()'
  | 'chance.profession()'
  | 'chance.phone()'
  // | 'chance.system.fileName()'
  // | 'chance.system.semver()'
  | 'chance.word()';
